---
http_interactions:
  - request:
      method: post
      uri: https://api.example.com/hoge
    response:
      status:
        code: 201
        message: Created
      headers:
        Content-Type:
        - application/json; charset=utf-8
      body:
        encoding: UTF-8
        string: |
          {
            "hoge": {
              "id":    1234,
              "fuga":  "GAHAHAHA!"
            }
          }
      http_version: 
    recorded_at: Sat, 01 Apr 2017 06:15:42 GMT
recorded_with: VCR 3.0.3
